apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: adwera/kub-auth-api
        env:
          - name: MONGO_URI
            value: 'mongodb://auth-mongo-service:27017/auth'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
